const rowss = [
  {
    id: 1,
    name: "Apple",
    color: "Red",
    weight: "150g",
    price: "$0.5",
    quantity: 10,
  },
  {
    id: 2,
    name: "Banana",
    color: "Yellow",
    weight: "120g",
    price: "$0.3",
    quantity: 20,
  },
  {
    id: 3,
    name: "Orange",
    color: "Orange",
    weight: "200g",
    price: "$0.6",
    quantity: 15,
  },
  {
    id: 4,
    name: "Grapes",
    color: "Purple",
    weight: "180g",
    price: "$0.8",
    quantity: 12,
  },
  {
    id: 5,
    name: "Strawberry",
    color: "Red",
    weight: "50g",
    price: "$1.2",
    quantity: 8,
  },
  {
    id: 6,
    name: "Pineapple",
    color: "Yellow",
    weight: "500g",
    price: "$2.0",
    quantity: 5,
  },
  {
    id: 7,
    name: "Watermelon",
    color: "Green",
    weight: "3000g",
    price: "$5.0",
    quantity: 2,
  },
  {
    id: 8,
    name: "Kiwi",
    color: "Brown",
    weight: "100g",
    price: "$1.0",
    quantity: 7,
  },
  {
    id: 9,
    name: "Mango",
    color: "Yellow",
    weight: "300g",
    price: "$1.5",
    quantity: 9,
  },
  {
    id: 10,
    name: "Peach",
    color: "Orange",
    weight: "200g",
    price: "$0.7",
    quantity: 11,
  },
];

export default rowss;
