// const rowss = [
//   {
//     id: 1,
//     uniqueId: "12345",
//     batchNo: "BATCH123",
//     medicineName: "DummyMed",
//     medicineCompany: "Dummy Pharma",
//     quantity: "50",
//     expiryDate: "2024-12-31",
//     purchaseDate: "2024-03-16",
//     type: "Tablet",
//     purchasePrice: "10.00",
//     salePrice: "15.00",
//     rackColour: "Red",
//     supplierNo: "SUP123",
//     supplierId: "SUPID123",
//     strength: "500mg",
//     description: "This is a dummy medicine description.",
//   },
//   {
//     id: 2,
//     uniqueId: "54321",
//     batchNo: "BATCH456",
//     medicineName: "DummyMed2",
//     medicineCompany: "Dummy Pharmaceuticals",
//     quantity: "100",
//     expiryDate: "2025-06-30",
//     purchaseDate: "2024-03-16",
//     type: "Capsule",
//     purchasePrice: "15.00",
//     salePrice: "20.00",
//     rackColour: "Blue",
//     supplierNo: "SUP456",
//     supplierId: "SUPID456",
//     strength: "250mg",
//     description: "This is another dummy medicine description.",
//   },
//   {
//     id: 3,
//     uniqueId: "67890",
//     batchNo: "BATCH789",
//     medicineName: "DummyMed3",
//     medicineCompany: "Generic Pharma",
//     quantity: "75",
//     expiryDate: "2023-10-15",
//     purchaseDate: "2024-03-16",
//     type: "Injection",
//     purchasePrice: "20.00",
//     salePrice: "25.00",
//     rackColour: "Green",
//     supplierNo: "SUP789",
//     supplierId: "SUPID789",
//     strength: "100mg",
//     description: "This is yet another dummy medicine description.",
//   },
//   {
//     id: 4,
//     uniqueId: "24680",
//     batchNo: "BATCH246",
//     medicineName: "DummyMed4",
//     medicineCompany: "Pharma Inc.",
//     quantity: "200",
//     expiryDate: "2024-08-20",
//     purchaseDate: "2024-03-16",
//     type: "Syrup",
//     purchasePrice: "8.00",
//     salePrice: "12.00",
//     rackColour: "Yellow",
//     supplierNo: "SUP246",
//     supplierId: "SUPID246",
//     strength: "200mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 5,
//     uniqueId: "13579",
//     batchNo: "BATCH357",
//     medicineName: "DummyMed5",
//     medicineCompany: "MediCorp",
//     quantity: "30",
//     expiryDate: "2024-11-25",
//     purchaseDate: "2024-03-16",
//     type: "Cream",
//     purchasePrice: "18.00",
//     salePrice: "22.00",
//     rackColour: "White",
//     supplierNo: "SUP357",
//     supplierId: "SUPID357",
//     strength: "50mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 6,
//     uniqueId: "80246",
//     batchNo: "BATCH802",
//     medicineName: "DummyMed6",
//     medicineCompany: "Health Pharmaceuticals",
//     quantity: "150",
//     expiryDate: "2025-02-28",
//     purchaseDate: "2024-03-16",
//     type: "Gel",
//     purchasePrice: "25.00",
//     salePrice: "30.00",
//     rackColour: "Transparent",
//     supplierNo: "SUP802",
//     supplierId: "SUPID802",
//     strength: "75mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 7,
//     uniqueId: "36980",
//     batchNo: "BATCH369",
//     medicineName: "DummyMed7",
//     medicineCompany: "Pharmaceutics Ltd.",
//     quantity: "80",
//     expiryDate: "2024-09-15",
//     purchaseDate: "2024-03-16",
//     type: "Ointment",
//     purchasePrice: "12.00",
//     salePrice: "18.00",
//     rackColour: "Brown",
//     supplierNo: "SUP369",
//     supplierId: "SUPID369",
//     strength: "150mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 8,
//     uniqueId: "97531",
//     batchNo: "BATCH975",
//     medicineName: "DummyMed8",
//     medicineCompany: "BioPharm",
//     quantity: "40",
//     expiryDate: "2024-10-10",
//     purchaseDate: "2024-03-16",
//     type: "Ointment",
//     purchasePrice: "12.00",
//     salePrice: "18.00",
//     rackColour: "Brown",
//     supplierNo: "SUP369",
//     supplierId: "SUPID369",
//     strength: "150mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 9,
//     uniqueId: "97531",
//     batchNo: "BATCH975",
//     medicineName: "DummyMed8",
//     medicineCompany: "BioPharm",
//     quantity: "40",
//     expiryDate: "2024-10-10",
//     purchaseDate: "2024-03-16",
//     type: "Ointment",
//     purchasePrice: "12.00",
//     salePrice: "18.00",
//     rackColour: "Brown",
//     supplierNo: "SUP369",
//     supplierId: "SUPID369",
//     strength: "150mg",
//     description: "Yet another dummy medicine description.",
//   },
//   {
//     id: 10,
//     uniqueId: "97531",
//     batchNo: "BATCH975",
//     medicineName: "DummyMed8",
//     medicineCompany: "BioPharm",
//     quantity: "40",
//     expiryDate: "2024-10-10",
//     purchaseDate: "2024-03-16",
//     type: "Ointment",
//     purchasePrice: "12.00",
//     salePrice: "18.00",
//     rackColour: "Brown",
//     supplierNo: "SUP369",
//     supplierId: "SUPID369",
//     strength: "150mg",
//     description: "Yet another dummy medicine description.",
//   },
// ];

// export default rowss;
